#--------------------------технические параметры для Hydra----------------------------------------
defaults:
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .
  job_logging:
    handlers:
      file:
        class: logging.NullHandler
#------------------------------------------------------------------------------------------------

#-----------------------------------Параметры конфигурации проекта--------------------------------
capture:
  source: test2.mp4                 # путь к файлу  или ID камеры (int)  или ссылка на URL поток


rendering:
  fps_buffer_size: 15       # количество кадров за которое производится расчет FPS
  width: None               # Ширина окна вывода (изображения)
  height: None              # Высота окна вывода (изображения)
#---------------------------------------------------------------------------------------------------