#--------------------------технические параметры для Hydra----------------------------------------
defaults:
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .
  job_logging:
    handlers:
      file:
        class: logging.NullHandler
#------------------------------------------------------------------------------------------------

#-----------------------------------Параметры конфигурации проекта--------------------------------
capture:
  source: test2.mp4                 # путь к файлу  или ID камеры (int)  или ссылка на URL поток

rendering:
  fps_buffer_size: 15       # количество кадров за которое производится расчет FPS
  width: None               # Ширина окна вывода (изображения)
  height: None              # Высота окна вывода (изображения)

detection:
  model_path: weights/yolov8m.pt  # Путь к модели
  conf: 0.45                      # Порог уверенности детектора (чем больше значение, тем меньше находит)
  classes: [2,3,5,7]              # 2: car, 3: motorcycle, 5: bus, 7: truck
  tracking: botsort.yaml          # Математические настройки алгоритма слежения (можно заменить на bytetrack.yaml)
  track_buffer: 60                # Время жизни трека в кадрах
#---------------------------------------------------------------------------------------------------